import { chromium } from 'playwright';
import fs from 'node:fs';
const browser = await chromium.launch( process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {} );
const page = await browser.newPage( { viewport: { width: 1300, height: 900 } } );
const errors = [];
page.on( 'pageerror', ( e ) => errors.push( e.message ) );
await page.goto( ( process.env.WP_BASE || 'http://127.0.0.1:8089' ) + '/wp-login.php' );
await page.fill( '#user_login', ( process.env.WP_USER || 'admin' ) ); await page.fill( '#user_pass', process.env.WP_PASS || 'admin' ); await page.click( '#wp-submit' );
await page.waitForURL( /wp-admin/ );
await page.goto( ( process.env.WP_BASE || 'http://127.0.0.1:8089' ) + '/wp-admin/plugins.php', { waitUntil: 'networkidle' } );
const notice = page.locator( '.notice', { hasText: 'All Effects' } );
console.log( 'notice count', await notice.count(), 'text:', ( await notice.innerText().catch( () => '' ) ).replace( /\s+/g, ' ' ) );
await page.screenshot( { path: 'plugins-notice.png' } );
const btn = notice.getByRole( 'button', { name: 'Delete the free edition' } );
console.log( 'button', await btn.count() );
await btn.click();
await page.waitForLoadState( 'networkidle' );
console.log( 'after: url', page.url(), 'free dir exists:', fs.existsSync( ( process.env.WP_PLUGINS_DIR || '/var/www/html/wp-content/plugins' ) + '/holo-image-styles' ), 'notice now:', await page.locator( '.notice', { hasText: 'All Effects' } ).count() );
console.log( 'errors', errors );
await browser.close();
